[flake8]
exclude =
    .git,
    __pycache__,
    .venv,
    */migrations/*,
    tests/*/conftest.py

# Игнорировать эти конкретные коды ошибок
ignore =
    E501,  # Line too long (Black)
    W503,  # Line break before binary operator
    E203,  # Whitespace before ':'

# Максимальная длина строки (если не игнорируется E501)
max-line-length = 88