[pytest]
python_files = *test*.py
python_classes = *Test*
markers =
    ui: tests for User Interface (UI) interactions
    api: tests for Application Programming Interface (API) endpoints
    positive: Mark test as a positive scenario.
    negative: Mark test as a negative scenario.

